source "https://rubygems.org"

# Jekyll for local development
gem "jekyll", "~> 4.3"

# Remote theme support for local testing
gem "jekyll-remote-theme"

# Plugins required by just-the-docs theme
gem "jekyll-seo-tag"
gem "jekyll-include-cache"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
